### ISSUE TITLE
Set params_extractor for Google::Gax.create_api_call

### ISSUE THREAD

**Issue by quartzmo** [googleapis/gapic-generator-ruby#104]
In order for gRPC API backends to route traffic efficiently, it is necessary for some values to be sent in HTTP headers as well as in the request payload.

Code generators should look at URL-based variables declared in the `google.api.http` annotation and transcribe these into the `x-goog-request-params` header in unary calls. A URL-based variable is a variable declared as a key in curly braces in the URI string. For example:

```
rpc CreateTopic(CreateTopicRequest) {
  option (google.api.http).post = "{parent=projects/*}/topics";
}
```

In this case, the applicable variable is parent, and it refers to the parent field in CreateTopicRequest.

Example from google-cloud-spanner:

```rb
                @list_databases = Google::Gax.create_api_call(
                  @database_admin_stub.method(:list_databases),
                  defaults["list_databases"],
                  exception_transformer: exception_transformer,
                  params_extractor: proc do |request|
                    {'parent' => request.parent}
                  end
                )
```

**Comment by blowmage** [comment]
The implementation has changed since this issue was created. Currently, these values are intended to be calculated in the client method and sent to the RPC. Each client now contains code that looks like this:

```ruby
  # Customize the options with defaults
  header_params = {} # { name: request.name }
  request_params_header = header_params.map { |k, v| "#{k}=#{v}" }.join("&")
  metadata = @metadata.merge "x-goog-request-params".freeze => request_params_header
  retry_policy = {} # retry_codes: [GRPC::Core::StatusCodes::UNAVAILABLE] }
  options.apply_defaults timeout: @timeout, metadata: metadata, retry_policy: retry_policy
```

The intention is that `header_params` contains a hash of names and request values that are then used to create the `x-goog-request-params` header value. So instead of generating a proc, we should be generating a hash.
