### ISSUE TITLE
Update google-protobuf dependency to >= 3.18 in gapic-common (add support for 4.x)

### ISSUE THREAD

**Issue by colinbendell** [googleapis/gapic-generator-ruby#1080]
The `gapic-common` v0.21.1 depends on `google-protobuf ~> 3.18` (2021 vintage). This approximately equal dependency prohibits major version jumps and parent projects aren't able to add dependencies using the 4.x series of `google-protobuf` (v4.27.1 is the latest). 

Can we update the dependency to:
```
spec.add_dependency 'google-protobuf', '>= 3.18', '< 5.0'
```

Further context, `google-cloud-ai_platform-v1` depends on `gapic-common` causing this implicit legacy gem dependency

**Comment by dazuma** [comment]
Thanks Colin. Yes, we need to update gapic-common, although we're also dependent on grpc updating before we can fully test. (I see you also opened https://github.com/grpc/grpc/issues/36891, thanks for doing that.) I'll see if we can get these prioritized.

**Comment by colinbendell** [comment]
@dazuma Thanks! I think you'll also want to do the same for the gapic-generator in this repo

**Comment by dazuma** [comment]
@colinbendell gapic-generator isn't part of the runtime stack so shouldn't affect your usage. Yes, we'll need to update it at some point soon, but we're very careful about its dependencies because of its critical role in the supply chain.

We have a brief release freeze in progress while some updates to our infrastructure are happening, but I hope to get the updated gapic-common gem out in the next day or so, or the very beginning of next week at the latest.
