### ISSUE TITLE
protobuf plugin output file paths are not customizable

### ISSUE THREAD

**Issue by quartzmo** [googleapis/gapic-generator-ruby#160]
@samphippen wrote in #159:

> Hey y'all, should the generated `_pb.rb` files etc be in `google_ads` not `googleads`? ... `google_ads` is desired, as that's what the `client.rb` and `credentials.rb` (gapic files) get generated in.

@blowmage replied:

> > Hey y'all, should the generated `_pb.rb` files etc be in `google_ads` not `googleads`?

> No. The files that the protobuf plugin creates will always match the path of original proto file. The file `google/ads/googleads/v1/common/ad_asset.proto` will be generated as `google/ads/googleads/v1/common/ad_asset_pb.rb`. We aren't touching those files, only creating them using the protobuf plugin.

**Comment by dazuma** [comment]
Sounds like this is a strong feature request from ads. And honestly it's going to be a strong request for cloud as well.

I can think of two options.
1. We reimplement the ruby and grpc_ruby plugins. It looks like other languages (e.g. python) have taken this route.
2. We add a postprocessing step (perhaps invoked from the docker entrypoint script)

**Comment by blowmage** [comment]
Either of those steps would preclude any interoperability with protos that are generated by the protobuf or grpc plugins. If a proto file with `import "google/ads/googleads/v1/common/ad_asset.proto"` was generated by the protobuf plugin, the generated ruby code would not be able to find/use the file generated by GAPIC.

The grpc gem ships with a runtime dependency on the googleapis-common-protos-types gem. So the expectation that the protobuf plugin is used to generate the Ruby code that uses grpc runs pretty deep. I'm not saying this isn't possible, I'm saying it may have unintended consequences.

**Comment by dazuma** [comment]
It's a good question of whether we care about any such "interoperability" use cases.

Here's some analysis of a few use cases:

*  **Interoperability with upstream runtime dependencies (like googleapis-common-protos)**. In this case, I'm pretty sure it doesn't matter, because all the dependencies should be in one direction. Any custom-compiled or moved protos that we generate in our clients would depend on the common protos (remaining in their standard locations) the same way they always have. We don't expect there ever to be cases of reverse dependencies, common protos "requiring" library-specific protos that we've custom-compiled or moved.

*  **A user wants to require one of the client library's `_pb.rb` files directly.** The file might not be in the "standard" location. The question then is whether we consider this a "supported" use case. I believe can (and do already) consider these files "internal" and that we don't support requiring them directly from user code. We could even rename them to emphasize this fact. Again, I don't think this case is a concern.

*  **A user builds their own protos using the standard tools.** Perhaps they wanted to "update" the protos used by the client library, or more likely, they want to use the proto types in their own code separate from the client. Now these user-built protos are incompatible with the client library, because if the library's copies of the protos are in different locations, both paths could get required, causing redefined constants and other name clashes. So this is a more serious issue. However, this case is _always_ going to be problematic even if we don't move our generated proto files, because the user might have built from a different version of the original `.proto` source, thus causing conflicts with the generated client library ruby code. So this is a case I don't think we can support either way.

So far I don't think I've found a problematic use case. Can anyone else think of one?

**Comment by quartzmo** [comment]
@blowmage @dazuma @samphippen I think we determined (offline) that:

1. The interoperability use cases above are not a concern for the user(s) who want these custom paths.
2. The solution for this issue will be in the form of rake task(s) for moving files and updating require paths, which will be invoked by [docker-entrypoint.sh](https://github.com/googleapis/gapic-generator-ruby/blob/master/docker-entrypoint.sh) after `protoc` produces its output.
3. The Ruby gapic generator will not do anything related to this issue.

**Comment by dazuma** [comment]
This has been addressed (for the ads case) by #165
