### ISSUE TITLE
Make generated code depend on google-cloud-env gem

### ISSUE THREAD

**Issue by quartzmo** [googleapis/gapic-generator-ruby#178]
Similar to #175

**Comment by blowmage** [comment]
@dazuma Do you want the non-cloud gems to use google-cloud-env in the configuration to lookup values?

**Comment by dazuma** [comment]
If a client actually does need to know info about its _google cloud_ environment (e.g. GCE-provided credentials), then yes we should use google-cloud-env.

**Comment by blowmage** [comment]
The googleauth gem already checks GCE for credentials, and google-cloud-env doesn't have any methods to check for them AFAIK. The most common usage of google-cloud-env is to lookup the `project_id`, but the microgenerator doesn't have any configuration for `project_id` because it doesn't need it. Is there anything the microgenerator directly needs to access the GCE for?

**Comment by dazuma** [comment]
I'm not sure. Not that I know of. If we're not needing any of this info at this point, we can just close this.

**Comment by blowmage** [comment]
K. Closing until we have a need for this dependency.
