### ISSUE TITLE
Don't exclude "normal" files from rubocop settings

### ISSUE THREAD

**Issue by dazuma** [googleapis/gapic-generator-ruby#191]
Currently there are some "normal" source files excluded from rubocop settings for cops such as Metrics/PerceivedComplexity. Ideally this won't be the case. Do one of the following:
* Go through and perform any necessary refactors so we can remove the exclusions.
* Alter our metrics settings globally to allow the complexity level we feel is appropriate
* Include comments on the specific methods that violate the rules _with cause_, but don't blanket exclude entire files because that could mask other issues in the file.

**Comment by blowmage** [comment]
Currently we exclude the following rules for all microgenerator clients due to the size and complexity of the RPC methods. It is important that the client classes only define methods for the RPCs, to limit potential naming conflicts, so those methods can be large and complex when multiple options are used (header params, pagination, etc.). The case equality rule is excluded because the Configuration classes use case equality in the config lookup.

* `Metrics/AbcSize`
* `Metrics/ClassLength`
* `Metrics/CyclomaticComplexity`
* `Metrics/LineLength`
* `Metrics/MethodLength`
* `Metrics/PerceivedComplexity`
* `Style/CaseEquality`

The `Naming/FileName` rule is also excluded for the cloud's gem file, because it needs to match the gem name, which have hyphens.
