### ISSUE TITLE
Client Documentation

### ISSUE THREAD

**Issue by landrito** [googleapis/gapic-generator-ruby#27]
## What
In [client.erb#22](https://github.com/googleapis/gapic-generator-ruby/blob/master/gapic-generator-cloud/templates/cloud/client.erb#L22), the documentation for the client is not being generated. This documentation should be the documentation of the service from the protos as well as the public attributes of the client.

## Data
The data for the client documentation can be accessed through the `Google::Gapic::Schema::Service#docs` method. This method returns a [`Google::Protobuf::SourceCodeInfo::Location`](https://github.com/ruby-protobuf/protobuf/blob/master/lib/protobuf/descriptors/google/protobuf/descriptor.pb.rb#L287) type in which you can access the leading, trailing, and leading detached comments. 

## How
Grab the comments from the docs method and format them as comments.

**Comment by blowmage** [comment]
This issue was referring to the old [client template](https://github.com/googleapis/gapic-generator-ruby/blob/c74380ae0c1a4a8c97bcfab6861521c5cba0945b/gapic-generator-cloud/templates/cloud/client.erb#L22) not generating detailed documentation. The [current client template](https://github.com/googleapis/gapic-generator-ruby/blob/41906a1d958704b996d7518805b5a8c701de6364/gapic-generator/templates/default/service/client/_client.erb#L17) is not much changed.

**Comment by dazuma** [comment]
Client-level docs have been added to the client class. We also need docs for the service module, and the package module, but those are covered by #389. Closing this as completed.
