### ISSUE TITLE
[transfer from gapic-generator] Ruby: Generate rubocop config and make sure generated clients pass rubocop.

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/gapic-generator-ruby#387]
https://github.com/googleapis/gapic-generator/issues/1120

**Comment by dazuma** [comment]
googleapis/gapic-generator#1120 has already been fixed in the microgenerator.

@hzyi-google Feel free to actually transfer issues to this repo if you want. Alternatively, if you just want to give us a list of links to existing issues from googleapis/gapic-generator (including the ones closed), we'd be happy to take that as well. I suspect that the microgenerator has already generally fixed, or rendered obsolete, most of them anyway.

**Comment by hzyi-google** [comment]
OK sounds good. I'll just transfer issues over. It's great most of the issues would go away naturally!
