### ISSUE TITLE
Authentincation link in readmes is rendering as a text

### ISSUE THREAD

**Issue by viacheslav-rostovtsev** [googleapis/gapic-generator-ruby#533]
see e.g. https://github.com/googleapis/google-cloud-ruby/tree/master/google-cloud-workflows-v1beta

**Comment by dazuma** [comment]
This is a common issue for Ruby projects: the syntax used for linking to other files is different between github markdown and Yardoc. The link in question is in yardoc format and works there: https://www.rubydoc.info/gems/google-cloud-workflows-v1beta/0.1.0

Generally our approach has been to use github syntax only for a repository's toplevel readme (which we expect is the most commonly seen document on github—and for monorepos doesn't get included in any one gem's yardoc anyway), and use Yardoc syntax for individual gem readmes.

**Comment by quartzmo** [comment]
We have an open issue from a google-cloud-ruby user: googleapis/google-cloud-ruby#8578.

I suggested a [possible solution](https://github.com/googleapis/google-cloud-ruby/issues/8578#issuecomment-758234550). Feel free to comment, it might help me move forward, especially since the original poster has not responded.

**Comment by dazuma** [comment]
Fixed
