### ISSUE TITLE
Missing _pb files

### ISSUE THREAD

**Issue by IlyaUmanets** [googleapis/gapic-generator-ruby#561]
After generating I see that `session` class requires `session_pb` files which is not exist after generating. What is wrong?

I following this section - https://github.com/googleapis/gapic-generator-ruby#build-and-install-the-generator

I tried to build `dialogflow`

**Comment by hkdevandla** [comment]
@viacheslav-rostovtsev , any updates on this?

**Comment by viacheslav-rostovtsev** [comment]
I can't repro it locally.
@IlyaUmanets is it still an issue?

**Comment by viacheslav-rostovtsev** [comment]
I figured out what's the issue here. If you go through the self-serve section, the generator will only give you the client libraries code. The protobuf and grpc code has to be generated separately via `protoc --ruby_out` and protoc's grpc plugin.
Docker and Bazel paths described in the readme do this for you, but the self-serve path does not.

**Comment by Abdullah-l** [comment]
Can we update the self-serve path to do this, I can't seem to figure it out :/
