### ISSUE TITLE
Document Proto classes defined in generated services

### ISSUE THREAD

**Issue by blowmage** [googleapis/gapic-generator-ruby#97]
Currently we have files created in a `docs` directory that document the types defined in protos required by the services that clients are generated for. We need to do something similar.

**Comment by landrito** [comment]
A couple of questions about these docs.

1) Since we don't want users to require the generated docs, do you think adding an exception to the file would be beneficial?

```rb
raise RuntimeError, "This file is for documentation purposes only, requiring this file is disallowed."
```

2) The docs do not show that these messages include the `Google::Protobuf::MessageExts` module. A simple solution would be to the generated documentation classes include this module.

```rb
module MyApi
  module V1
    class Request
      include Google::Protobuf::MessageExts
    end
  end
end
```

3) The docs we are supplying right now do a good job at documenting the fields of a message but do not do a good job at documenting the common message methods.

Unfortunately protobuf does not expose a `Message` super class but rather binds those methods to the messages directly when the messages are registered [here](https://github.com/protocolbuffers/protobuf/blob/master/ruby/ext/google/protobuf_c/message.c#L720-L749). 

I think it would be awesome if we added these methods to the documentations somehow. I think we have a couple of options if we'd like to add them:

- Generate the documentation for those methods on every fake documentation class
- Create a create a fake super class (example below)
```rb
module Google
  module Protobuf
    class Message
       ...
       # Returns the message as a Ruby Hash object, with keys as symbols.
       # @return [Hash] the message as a ruby
       def to_h
       end
       ...
    end  
  end
end
```
```rb
module MyApi
  module V1
    class Request < Google::Protobuf::Message
    end
  end
end
```
This has the benefit of not repeating this documentation, but I don't think that this is a good approach because it might cause users to depend on the superclass that doesn't exist.

**Comment by blowmage** [comment]
I prefer the approach in 2, but it also looks like these classes extend `ClassMethods` as well:

```ruby
module MyApi
  module V1
    class Request
      include Google::Protobuf::MessageExts
      extend Google::Protobuf::MessageExts::ClassMethods
    end
  end
end
```

For 3, I think it might make more sense to document those common methods on `MessageExts` and `MessageExts::ClassMethods` than to create a `Message` class that doesn't exist. The only problem is that if users inspect those modules they wouldn't find them, but perhaps we can note that in those methods' documentation.

```ruby
module Google
  module Protobuf
    module MessageExts
      ...
      # Returns the message as a Ruby Hash object, with keys as symbols.
      # (Not actually part of MessageExts, but created when included into a class.)
      # @return [Hash] the message as a ruby
      def to_h
      end
      ...

      module ClassMethods
        ...
        # Encodes the resource object as a Protobuf stream.
        # (Not actually part of MessageExts::ClassMethods, but created when extended on a class.)
        # @return [Object] the resource object
        # @return [String] the Protobuf stream
        def encode resource
        end
        ...
      end
    end
  end
end
```

**Comment by landrito** [comment]
> For 3, I think it might make more sense to document those common methods on MessageExts and MessageExts::ClassMethods than to create a Message class that doesn't exist. 

Ah agreed I like this approach better than both approaches I proposed.

> The only problem is that if users inspect those modules they wouldn't find them, but perhaps we can note that in those methods' documentation.

I think that would be fine, at least for a first pass then in the future if we get some negative feedback we can reconsider.

**Comment by landrito** [comment]
Taking this on since it will help me figure out whats wrong with enums.
